import React from 'react';
import s from './Settings.module.scss';

const Settings = () =>{
    return(
        <div className={s.wrap}>
            <h1 className={s.title}>Hello world</h1>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam consectetur consequatur dicta dolorum, eius eos facilis laborum neque numquam obcaecati perspiciatis porro quae quam quis quo, repellat, totam voluptatibus.</span><span>Aperiam asperiores autem debitis deleniti doloribus eaque enim error ex exercitationem explicabo, facilis fuga, fugit impedit ipsam laudantium optio perferendis quam quibusdam quis quisquam reiciendis soluta suscipit ullam vitae voluptatibus!</span><span>Expedita, incidunt nesciunt non perspiciatis totam veritatis voluptate? A accusantium assumenda delectus, distinctio dolor doloribus, et illum magnam nemo odit placeat provident recusandae reiciendis repellat sequi similique sit totam voluptas.</span><span>A, aspernatur consectetur culpa doloremque ducimus ea eaque eligendi enim exercitationem expedita illo libero magni minima officiis quam quia quis similique sunt unde velit. Atque dolore eum labore placeat temporibus?</span><span>Eaque eius esse ex fugiat in iste nam neque reprehenderit ut. Blanditiis dignissimos, dolor facilis fugit harum id iure libero magnam maiores necessitatibus nihil numquam placeat reiciendis sit unde voluptas!</span><span>Aliquam culpa, delectus fugiat iure labore magni maiores minima necessitatibus pariatur quaerat. Doloribus incidunt laborum provident ratione tenetur! Cum cumque dignissimos id magnam maiores molestias nemo perspiciatis quos reprehenderit ullam.</span><span>Amet aperiam deserunt est fuga, magnam perspiciatis quo. Accusamus alias asperiores assumenda beatae, consectetur dolorem eaque, est, labore minus nemo nihil nobis perferendis qui quia quos repellendus temporibus totam ullam.</span><span>Amet, asperiores consequatur dolor eius maiores quae quaerat reprehenderit soluta unde ut. Accusantium aliquid, aspernatur deserunt dolores eaque eos, in laborum neque nobis odit, quas repudiandae sapiente soluta veritatis voluptate?</span><span>Alias aliquid aperiam architecto deserunt dolorum, ea minima mollitia, nam nulla quisquam quod rerum, voluptate? Exercitationem fugiat itaque magnam optio vero. Asperiores minima nemo perferendis reprehenderit sed! Beatae odio, reprehenderit.</span><span>Ab aliquam amet architecto consequuntur culpa deleniti dolorem, ducimus, ea eveniet exercitationem facere fugiat illum in ipsa labore minima necessitatibus odio omnis optio perferendis perspiciatis, quis quisquam rem repellendus vitae!</span></p>
        </div>
    )
}

export default Settings;